version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ravr-backend
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_DSN: host=db user=postgres password=postgres dbname=ravr-backend port=5432 sslmode=disable
      JWT_SECRET: secret
    depends_on:
      - db
