services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ravr-backend
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  migrator:
    image: migrate/migrate:v4.17.1
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/ravr-backend?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      JWT_SECRET: secret
    depends_on:
      migrator:
        condition: service_completed_successfully

volumes:
  postgres_data:

