version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: echo_mvp
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_DSN: host=db user=postgres password=postgres dbname=echo_mvp port=5432 sslmode=disable
      JWT_SECRET: secret
    depends_on:
      - db
