// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.ravr-site.io/support",
            "email": "support@ravr-site.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/leaderboard/update": {
            "post": {
                "description": "Обновляет рейтинги пользователей за указанный период (weekly, monthly)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leaderboard"
                ],
                "summary": "Обновление рейтингов",
                "parameters": [
                    {
                        "type": "string",
                        "default": "weekly",
                        "description": "Период (daily, weekly, monthly)",
                        "name": "period",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerSuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Аутентифицирует пользователя и возвращает JWT токен",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход в систему",
                "parameters": [
                    {
                        "description": "Учетные данные",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Создает нового пользователя с указанными учетными данными",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает данные текущего аутентифицированного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Профиль пользователя",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerUserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/leaderboard": {
            "get": {
                "description": "Возвращает список пользователей, отсортированных по опыту, с изменением позиции",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "leaderboard"
                ],
                "summary": "Таблица лидеров",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Максимальное количество записей (по умолчанию 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerLeaderboardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/lessons": {
            "get": {
                "description": "Возвращает список уроков определенного типа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lessons"
                ],
                "summary": "Получение уроков по типу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Тип урока",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerLessonsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/lessons/complete": {
            "post": {
                "description": "Обновляет статистику пользователя при завершении урока",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lessons"
                ],
                "summary": "Завершение урока",
                "parameters": [
                    {
                        "description": "Данные о прохождении урока",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CompleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CompleteLessonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/lessons/{id}": {
            "get": {
                "description": "Возвращает детальную информацию об уроке по его ID, включая полные данные урока",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lessons"
                ],
                "summary": "Получение детальной информации урока",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID урока",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerLessonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/results/save": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Save result for a lesson",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Results"
                ],
                "summary": "Save result",
                "parameters": [
                    {
                        "description": "Save result request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.saveResultRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResultSaveResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/responses.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.CompleteLessonResponse": {
            "type": "object",
            "properties": {
                "completedTime": {
                    "description": "Время завершения урока",
                    "type": "string"
                },
                "earnedXP": {
                    "description": "Заработанный опыт за текущий урок",
                    "type": "integer"
                },
                "experience": {
                    "description": "Текущий опыт пользователя",
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "controller.CompleteRequest": {
            "type": "object",
            "properties": {
                "completionTime": {
                    "type": "string"
                },
                "earnedExperience": {
                    "type": "integer"
                },
                "lessonId": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "controller.SwaggerLeaderboardResponse": {
            "description": "Ответ с таблицей лидеров",
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "experience": {
                                "type": "integer",
                                "example": 1500
                            },
                            "first_name": {
                                "type": "string",
                                "example": "John"
                            },
                            "last_name": {
                                "type": "string",
                                "example": "Doe"
                            },
                            "position": {
                                "type": "integer",
                                "example": 1
                            },
                            "trend": {
                                "type": "string",
                                "example": "up"
                            },
                            "user_id": {
                                "type": "integer",
                                "example": 1
                            },
                            "username": {
                                "type": "string",
                                "example": "johndoe"
                            }
                        }
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "controller.SwaggerLessonResponse": {
            "description": "Ответ с данными одного урока",
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/service.Lesson"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "controller.SwaggerLessonsResponse": {
            "description": "Ответ со списком уроков",
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.LessonByType"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "controller.SwaggerMessageResponse": {
            "description": "Успешный ответ с сообщением",
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "controller.SwaggerResultSaveResponse": {
            "description": "Ответ с данными одного урока",
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/service.Leaderboard"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "controller.SwaggerSuccessResponse": {
            "description": "Успешный ответ с сообщением для Swagger",
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "controller.SwaggerTokenResponse": {
            "description": "Успешный ответ с токеном авторизации",
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "token": {
                            "type": "string",
                            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                        }
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "controller.SwaggerUserProfileResponse": {
            "description": "Ответ с данными профиля пользователя",
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "first_name": {
                            "type": "string",
                            "example": "John"
                        },
                        "id": {
                            "type": "integer",
                            "example": 1
                        },
                        "last_name": {
                            "type": "string",
                            "example": "Doe"
                        },
                        "username": {
                            "type": "string",
                            "example": "johndoe"
                        }
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "controller.loginRequest": {
            "description": "Запрос на вход в систему",
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "secret123"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "controller.registerRequest": {
            "description": "Запрос на регистрацию нового пользователя",
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "first_name": {
                    "type": "string",
                    "example": "John"
                },
                "last_name": {
                    "type": "string",
                    "example": "Doe"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "secret123"
                },
                "username": {
                    "type": "string",
                    "minLength": 3,
                    "example": "johndoe"
                }
            }
        },
        "controller.saveResultRequest": {
            "type": "object",
            "properties": {
                "lesson_id": {
                    "type": "string",
                    "example": "1"
                },
                "time_taken": {
                    "type": "integer",
                    "example": 120
                }
            }
        },
        "responses.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "responses.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/responses.ErrorInfo"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "service.Leaderboard": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.Result"
                    }
                },
                "userPosition": {
                    "type": "integer"
                }
            }
        },
        "service.Lesson": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "lesson_data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "level": {
                    "type": "integer"
                },
                "mode": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "service.LessonByType": {
            "type": "object",
            "properties": {
                "easyId": {
                    "type": "integer"
                },
                "hardId": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                }
            }
        },
        "service.Result": {
            "type": "object",
            "properties": {
                "position": {
                    "type": "integer"
                },
                "timeTaken": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                },
                "xp": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer \u003ctoken\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "RAVR Backend API",
	Description:      "JWT Authorization header using the Bearer scheme. Example: \"Authorization",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
