name: Java CI with Maven

on:
  push:
    branches: [ "feature/BCK-3" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build docker image
        run: docker build -t ravr-backend:v0.0.1 .

      - name: View docker images
        run: docker images

      - name: See package
        run: ls -la