name: Java CI with Maven

on:
  push:
    branches: [ "feature/BCK-3" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check docker
        run: docker --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: docker build --platform linux/amd64,linux/arm64 --push -t ravr-backend:v0.0.1 .
#
#      - name: Set up JDK 23
#        uses: actions/setup-java@v4
#        with:
#          java-version: '23'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml

      - name: See package
        run: ls -la