name: Java CI with Maven

on:
  push:
    branches: [ "feature/BCK-3" ]

env:
  DOCKER_IMAGE_REPOSITORY: fastrapier1/ravr-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build docker image
        run: docker build --push -t ${DOCKER_IMAGE_REPOSITORY}:${GITHUB_REF##*/} .